version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@types/react-native"
    versions:
    - 0.63.50
    - 0.63.51
    - 0.63.52
    - 0.64.0
    - 0.64.1
    - 0.64.2
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: reg-suit
    versions:
    - 0.10.14
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - 6.1.16
    - 6.1.17
    - 6.1.18
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
  - dependency-name: "@storybook/theming"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
  - dependency-name: reg-notify-github-plugin
    versions:
    - 0.10.12
    - 0.10.14
  - dependency-name: reg-publish-s3-plugin
    versions:
    - 0.10.10
  - dependency-name: vercel
    versions:
    - 21.2.1
